"""Execution identity: every execute() call gets a request_id, distinct
executions get distinct ids, and ids are never generated by the agent
nodes themselves (they only read what the runtime already put in config).
"""

import pytest

import main
import runtime as nexus_runtime


class _FakeMessage:
    def __init__(self, content):
        self.content = content


@pytest.fixture(autouse=True)
def _fake_llm_calls(monkeypatch):
    monkeypatch.setattr(
        main, "_call_classifier", lambda messages: main.MessageClassifier(message_type="coding")
    )
    monkeypatch.setattr(main, "_call_llm", lambda messages: _FakeMessage("stub reply"))


def test_new_thread_id_and_new_request_id_are_unique_and_prefixed():
    thread_ids = {nexus_runtime.new_thread_id() for _ in range(50)}
    request_ids = {nexus_runtime.new_request_id() for _ in range(50)}

    assert len(thread_ids) == 50
    assert len(request_ids) == 50
    assert all(t.startswith("thread-") for t in thread_ids)
    assert all(r.startswith("req-") for r in request_ids)


async def test_execute_generates_a_request_id(tmp_path):
    db_path = str(tmp_path / "req.sqlite")
    async with nexus_runtime.create_runtime(main.graph_builder, checkpoint_db=db_path) as session:
        result = await session.execute(nexus_runtime.new_thread_id(), "hi")

    assert result.request_id
    assert result.request_id.startswith("req-")


async def test_different_executions_get_different_request_ids(tmp_path):
    db_path = str(tmp_path / "req.sqlite")
    async with nexus_runtime.create_runtime(main.graph_builder, checkpoint_db=db_path) as session:
        thread_id = nexus_runtime.new_thread_id()
        first = await session.execute(thread_id, "one")
        second = await session.execute(thread_id, "two")

    assert first.request_id != second.request_id
    # Same thread across both executions, though.
    assert first.thread_id == second.thread_id == thread_id


def test_node_functions_read_request_id_from_config_rather_than_generate_it():
    # A node given a config carrying a request_id must use exactly that id,
    # never mint its own -- id generation is the runtime's job only.
    config = {"configurable": {"request_id": "req-supplied-by-runtime", "thread_id": "t1"}}
    request_id, thread_id = main._context_from_config(config)
    assert request_id == "req-supplied-by-runtime"
    assert thread_id == "t1"


def test_context_from_config_defaults_when_config_is_absent():
    # Node functions must stay callable without a config (Phase 0 test
    # style, and any future caller that doesn't route through the runtime).
    request_id, thread_id = main._context_from_config(None)
    assert request_id == "unknown"
    assert thread_id == "unknown"
